// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWWLfpYP3YK4NGKd0XHaUPurGWnD1Wl0',
    appId: '1:214688692694:web:305b34fab947b731fdcc77',
    messagingSenderId: '214688692694',
    projectId: 'firebase0090',
    authDomain: 'fir-0090.firebaseapp.com',
    storageBucket: 'firebase0090.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXC1i2G3JC3Pden2XCTcBCUZM8C3nSS0',
    appId: '1:214688692694:android:f4e0a818c514566efdcc77',
    messagingSenderId: '214688692694',
    projectId: 'firebase0090',
    storageBucket: 'firebase0090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JQ-W9C4mK6t-q01KWoIejJFJWOQKdPc',
    appId: '1:214688692694:ios:9dd78a8378ed3536fdcc77',
    messagingSenderId: '214688692694',
    projectId: 'firebase0090',
    storageBucket: 'firebase0090.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JQ-W9C4mK6t-q01KWoIejJFJWOQKdPc',
    appId: '1:214688692694:ios:f062f6b57b140cf4fdcc77',
    messagingSenderId: '214688692694',
    projectId: 'firebase0090',
    storageBucket: 'firebase0090.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
